name: app
description: "Expenses App"

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.5.3
  flutter: 3.24.3

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  freezed_annotation: 2.4.4
  flutter_bloc: 8.1.6
  get_it: 7.7.0
  dartz: 0.10.1
  flutter_svg: 2.0.10+1
  mockito: 5.4.4
  json_annotation: 4.9.0
  intl: 0.19.0
  retrofit: 4.5.0
  equatable: 2.0.5
  injectable: 2.3.0
  dio: 5.7.0
  logger: 2.4.0
  package_info_plus: 8.0.2
  shared_preferences: 2.3.2
  flutter_screenutil: 5.9.3
  fluro: ^2.0.5
  dropdown_button2: 2.3.9
  lottie: ^3.1.3
  fluttertoast: ^8.2.12
  photo_view: ^0.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: 2.4.12
  freezed: 2.5.7
  json_serializable: 6.8.0
  injectable_generator: 2.4.0
  retrofit_generator: 9.3.0
  flutter_gen_runner: 5.7.0
  flutter_lints: 4.0.0

flutter_gen:
  output: lib/core/gen/assets.gen.dart
  integrations:
    flutter_svg: true
  fonts:
    enabled: false
  colors:
    enabled: false

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/shared/
    - assets/images/tastes/
    - assets/lottie/
